sonar.projectKey=RAFAELMH809_DSW02-PRACTICA01
sonar.organization=rafaelmh809
sonar.sources=src/main/java,frontend/src
sonar.tests=src/test/java,frontend/src
sonar.java.binaries=target/classes
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info,frontend/coverage/frontend/lcov.info
